app/helpers/application_helper.rb
app/models/appointment.rb
app/models/appointment_type.rb
app/models/convict.rb
app/models/notification.rb
app/models/phone.rb
app/models/place.rb
app/models/slot.rb
app/services/sendinblue_adapter.rb
spec/factories/notification_types.rb
spec/models/convict_spec.rb
spec/models/notification_spec.rb
spec/models/phone_spec.rb

Hi,
I had a look at the codebase and it looks good overall :)
I suggested a few changes, feel free to merge or pick whatever you find relevant.
I did a bit a refactoring around several axis:
- methods visibility: keep private methods private
- tell dont ask: basically they `full?` method
- I also gathered phone related code in a module
I would be more concerned about database structure: constraints, default values etc. This could require some more work.
Another thing I would think about is the way phone numbers are currently handled. Is a 10 number format the way to go? What if you happen to need to deal with international numbers?
Hope this will help!

Suggestions

---

app/assets/stylesheets/bex.scss
app/views/bex/agenda_jap.html.erb
app/views/bex/agenda_spip.html.erb
spec/features/bex_spec.rb

change bex spip agenda layout, now a copy of bex jap agenda layout

---

app/javascript/packs/appointment_show.js
app/views/appointments/_missed_appointment_modal.html.erb
app/views/appointments/show.html.erb
spec/features/appointments_spec.rb

https://trello.com/c/AyADiaxa/380-ajouter-la-question-la-ppsmj-sest-elle-pr%C3%A9sent%C3%A9e-au-rdv-en-haut-de-la-page-infos-rdv

Allow appointment fulfilment on appointment#show

---

app/models/appointment.rb
app/views/appointments/show.html.erb
spec/features/appointments_spec.rb
spec/models/appointment_spec.rb

https://trello.com/c/6JTGS13X/442-est-ce-normal-que-lencadr%C3%A9-la-ppsmj-sest-elle-pr%C3%A9sent%C3%A9e-au-rdv-saffiche-alors-que-la-date-du-rdv-nest-pas-encore-pass%C3%A9e

fix bug appointment#show

---

app/assets/stylesheets/index.scss
app/assets/stylesheets/slots.scss
app/controllers/slots_batches_controller.rb
app/controllers/slots_controller.rb
app/views/slots/index.html.erb
config/locales/fr.yml
config/routes.rb
spec/features/slots_spec.rb

https://trello.com/c/4WDKQF76/775-une-administratrice-centrale-peut-fermer-des-cr%C3%A9neaux-en-s%C3%A9rie

allow to batch close slots

---

app/assets/stylesheets/errors.scss
app/controllers/appointment_types_controller.rb
app/models/notification_type.rb
app/views/appointment_types/edit.html.erb
config/locales/fr.yml
spec/features/appointment_types_spec.rb
spec/models/notification_type_spec.rb

Validate format template

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/appointments.scss
app/assets/stylesheets/convicts.scss
app/assets/stylesheets/index.scss
app/views/appointments/index.html.erb
config/locales/fr.yml
spec/features/appointments_spec.rb

Ajout des boutons de controle du statut des rdv sur l'index des rdv.
https://trello.com/c/KztnJLvQ/372-refonte-ticket-rdv-du-jour-3-3-indiquer-absence-pr%C3%A9sence

Allow appointment fulfilment on appointment index

---

app/assets/stylesheets/bex.scss
app/controllers/bex_controller.rb
app/helpers/bex_helper.rb
app/models/agenda.rb
app/models/organization.rb
app/views/bex/agenda_jap.html.erb
app/views/bex/agenda_spip.html.erb
config/locales/fr.yml
spec/features/bex_spec.rb

https://trello.com/c/xfWGbrMI/850-corriger-le-tableau-sorties-daudience-spip-et-sap

Use real data in BEX pages

---

app/helpers/slots_helper.rb
app/models/agenda.rb
app/models/appointment.rb
app/models/convict.rb
app/models/place.rb
app/models/slot.rb
app/models/user.rb
app/policies/agenda_policy.rb
app/policies/appointment_policy.rb
app/policies/convict_policy.rb
app/policies/place_policy.rb
app/policies/slot_policy.rb
app/views/appointments/index.html.erb
app/views/slots/index.html.erb
app/views/users/appointments/index.html.erb
spec/features/appointments_spec.rb
spec/features/convicts_spec.rb
spec/features/notifications_spec.rb
spec/features/places_spec.rb
spec/features/slot_types_spec.rb
spec/features/slots_spec.rb
spec/models/agenda_spec.rb
spec/models/appointment_spec.rb
spec/models/convict_spec.rb
spec/models/place_spec.rb
spec/models/slot_spec.rb
spec/models/user_spec.rb

https://trello.com/c/0FbZVHjb/1210-faire-fonctionner-le-systeme-avec-un-service-sur-deux-d%C3%A9partements

Adjust scopes for multi department organization

---

app/views/devise/sessions/new.html.erb

related to https://www.notion.so/monsuivijustice/Carnet-de-sprint-a14a1baa35314d0eaa82c5c9a540b516?p=8e2aa8519299417db82200cf00e8e1ad&pm=s

Allow to display password on login

---

app/models/appointment_type.rb

related to https://www.notion.so/monsuivijustice/BUG-une-CPIP-ne-voit-pas-son-rdv-81f21ade6b79492cbe0a80c8dc7efef3

Fix assignable types

---

app/jobs/update_convict_phone_job.rb
app/models/convict.rb
app/services/mon_suivi_justice_public_api/convict.rb

related to: https://www.notion.so/monsuivijustice/PPSMJ-lors-d-un-changement-de-coordonn-es-par-un-CPIP-je-garde-acc-s-mon-compte-et-je-suis-pr-ve-402b8bcf1def479da4e4a68ac850daa6
blocked by: https://github.com/betagouv/msj-public-back/pull/8/files

Update ppsmj login and phone number change

---

app/controllers/organizations_controller.rb
app/policies/organization_policy.rb
app/views/organizations/_mappings_edition.html.erb
app/views/organizations/edit.html.erb
app/views/organizations/index.html.erb
spec/policies/organizaton_policy_spec.rb

relates to https://www.notion.so/monsuivijustice/Visibilit-de-l-onglet-service-a120aa2151ff4070acc58cf685f9a120

New edition policy and views for organization model

---

app/views/devise/invitations/new.html.erb

related to: https://www.notion.so/monsuivijustice/Faire-une-passe-test-sur-l-application-PPSMJ-05bacc618bc24dd4805a6dce293a320f

Allow local_admin to create agent only in their service

---

app/controllers/appointments_controller.rb
app/policies/appointment_policy.rb
app/views/shared/_appointment_card.html.erb

related to https://www.notion.so/monsuivijustice/RDV-non-renseign-s-ne-plus-faire-apparaitre-l-encadr-rouge-sur-la-page-profil-de-la-PPSMJ-6-mois--7de95848267b41969fdccc7a997a39d2

Hide rdv after 6 month

---

app/views/convicts/new.html.erb

related to https://www.notion.so/monsuivijustice/Focus-sur-le-champ-nom-la-cr-ation-d-une-PPSMJ-1eaa0041eb904b069bf3097041ad6c56

Auto focus on convict name when creating a new convict

---

app/views/devise/invitations/new.html.erb

Relates to https://www.notion.so/monsuivijustice/Bug-la-cr-ation-d-un-compte-agent-par-un-agent-hors-admin-central-ne-fonctionne-pas-bc3194753aa540f8afeb1d5c5029ce50

fix agents creation form

---

app/dashboards/convict_dashboard.rb
app/dashboards/user_dashboard.rb

relates to https://www.notion.so/monsuivijustice/Possibilit-de-rechercher-dans-l-interface-admin-par-PPSMJ-ID-e95951a9ccee4884b52db7364ca61dfc

modified administrate conf

---

app/helpers/organization_helper.rb
app/models/convict.rb
app/policies/agenda_policy.rb
app/policies/place_policy.rb
app/views/places/edit.html.erb
app/views/places/new.html.erb
spec/policies/place_policy_spec.rb

related to https://www.notion.so/monsuivijustice/Habilitation-greffe-SAP-af4451724a5b40ac8543c444f0c8fb11?pvs=4

Habilitation greffe sap

---

app/jobs/sms_delivery_job.rb
app/policies/users/user_notification_policy.rb

fix sentry errors

---

app/dashboards/place_dashboard.rb
app/views/admin/places/index.html.erb
config/routes.rb

relates to https://www.notion.so/monsuivijustice/Cr-er-une-page-r-cap-des-lieux-ayant-le-lien-g-n-rique-60b00fb40e6c40d3a7a69ee8c497b6a1?pvs=4

added administrate routes for places and a nice filter

---

app/assets/stylesheets/bex.scss
app/assets/stylesheets/organizations.scss
app/controllers/bex_controller.rb
app/controllers/organizations_controller.rb
app/javascript/controllers/appointment_extra_field_display_controller.js
app/models/appointment_type.rb
app/models/extra_field.rb
app/models/organization.rb
app/views/abyme/_extra_field_fields.html.erb
app/views/appointments/new.html.erb
app/views/bex/agenda_jap.html.erb
app/views/bex/agenda_jap_pdf.html.erb
app/views/bex/agenda_spip.html.erb
app/views/bex/agenda_spip_pdf.html.erb
app/views/organizations/edit.html.erb
config/locales/fr.yml
db/migrate/20230309093547_create_join_table_appointment_type_extra_field.rb
db/schema.rb

relate to https://www.notion.so/monsuivijustice/Adapter-l-ajout-de-colonnes-optionnelles-a-la-sortie-d-audience-SPIP-d7c543ad2fec4746ae0c6c88efeba37b?pvs=4

Optionnal column spip

---

app/jobs/appi_import_job.rb

we need to avoid to leak convict data on staging

anonymise import on staging

---

app/helpers/users_helper.rb
app/views/users/edit.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb
config/initializers/simple_form.rb
config/locales/fr.yml

Dsfr agent

---

app/assets/stylesheets/layout.scss
app/controllers/home_controller.rb
app/views/layouts/agent_interface.html.erb
config/locales/devise.views.fr.yml
spec/features/home_spec.rb

Relates to : https://www.notion.so/monsuivijustice/6699b81d72ca4a83a91f5cdf5040aa3b?v=a645138367cd4492a8ff3d90a25ecbe4&p=367946aa2cd4470ea08cf75c40f24ce6&pm=s

added mep alert

---

app/controllers/invitations_controller.rb
app/views/devise/invitations/new.html.erb
config/initializers/devise.rb
config/locales/fr.yml

Relates to : https://www.notion.so/monsuivijustice/Validations-de-front-lors-d-erreur-dans-la-cr-ation-des-invitations-agents-27ae9dbf17e24e4ea68005ac7cb1cf5b

added validations for first_name and last_name and changed devise conf

---

app/controllers/appointments_controller.rb
app/helpers/organization_helper.rb
app/views/appointments/index.html.erb
app/views/appointments/show.html.erb
app/views/shared/_appointment_card.html.erb
app/views/shared/_appointments_table.html.erb
config/locales/fr.yml
spec/helpers/organization_helper_spec.rb

related to https://www.notion.so/monsuivijustice/Carnet-de-sprint-a14a1baa35314d0eaa82c5c9a540b516?p=8e90f7bdee664f4a9dadb1f93166d7d3&pm=s

Filter by cpip

---

app/views/slots/index.html.erb

related to https://www.notion.so/monsuivijustice/Bug-Impossible-de-fermer-les-creneaux-en-batch-9105b2bc794947459a9b1b5c3602d6db?pvs=4

fix slot batch cancel

---

app/models/user.rb
app/views/home/home.html.erb
config/locales/fr.yml

related to https://www.notion.so/monsuivijustice/Int-grer-phrase-de-bienvenue-sur-page-d-accueil-c5b7f6ca5a3c430e945bd310a2635b57?pvs=4

Pimp home page

---

app/assets/stylesheets/appointments.scss
app/assets/stylesheets/dsfr_fix.scss
app/assets/stylesheets/variables.scss
app/views/shared/_appointment_card.html.erb

related to https://www.notion.so/monsuivijustice/En-tant-qu-agent-habilit-j-aimerais-pouvoir-annuler-un-RDV-depuis-l-index-1f0187ed4a8a4c56a124ebb243ae123e?pvs=4

Add cancel button to appointments

---

app/views/convicts/edit.html.erb

related to https://www.notion.so/monsuivijustice/Incoh-rence-dans-le-formulaire-new-et-edit-des-PPSMJs-8865826db1f54b9b86c9ab52ec058782?pvs=4

Remove Live Abroad and homeless when not using inter-ressort

---

app/views/home/_home_stats.html.erb
app/views/home/home.html.erb
config/locales/fr.yml

related to: https://www.notion.so/monsuivijustice/Les-stats-sont-nouveau-accessibles-tous-les-utilisateurs-514cef2b170541e58ccfe99e82213418?pvs=4

Add back the statistics to the home page

---

lib/tasks/convicts.rake

related to https://www.notion.so/monsuivijustice/Avoir-la-possibilit-de-faire-un-import-APPI-dans-un-Si-ge-plut-t-que-dans-un-service-44459d045a4242f98b252f24a226df51?pvs=4

Rake to import convict into an organization from another organization

---

app/models/convict.rb

relates to https://www.notion.so/monsuivijustice/La-m-thode-check_duplicates-des-convicts-cherche-aussi-parmi-les-PPSMJ-archiv-es-ca87bed7de834c5dbdbf565e4d9f77ea?pvs=4

added discard kept method to the find duplicates method

---

app/models/organization.rb
config/initializers/abyme.rb
db/seeds.rb

Fix post deploy hook issue (db:seed crashes) which could be due to https://github.com/rails/rails/issues/29112

Fix review apps v2

---

app/assets/stylesheets/appointments.scss
app/controllers/appointments_reschedules_controller.rb
app/policies/appointments_reschedules_policy.rb
app/views/appointments_reschedules/new.html.erb
spec/policies/appointments_reschedules_policy_spec.rb

Relates to https://www.notion.so/monsuivijustice/La-replanification-est-toujours-possible-pour-les-greffe-sap-et-admin-locaux-33a02cac87c34fd391644d4a8e91e0c4?pvs=4

created dedicated policy for reschedules

---

app/controllers/slot_types_batches_controller.rb
app/views/slot_types/index.html.erb
config/locales/fr.yml
spec/features/slot_types_spec.rb

Zero interval slot types

---

app/controllers/bex_controller.rb
app/policies/bex_policy.rb
app/policies/place_policy.rb

Relates to 
https://www.notion.so/monsuivijustice/Un-agent-BEX-Greff-SAP-ou-Admin-local-ne-doit-avoir-acc-s-qu-aux-lieux-de-son-service-dans-l-onglet-efa42dd69cbb4ea298d1e0ab91219242?pvs=4

updated place policy

---

app/controllers/slots_controller.rb
app/policies/slot_policy.rb
app/views/slots/index.html.erb
config/locales/fr.yml

[MSJ-581] Display filter to show full slots

---

app/models/appointment.rb
app/models/concerns/transfert_validator.rb
app/models/slot.rb
config/locales/fr.yml

Improve place transfert flash

---

spec/features/appointments_spec.rb
spec/jobs/prepare_place_transfert_job_spec.rb
spec/models/agenda_spec.rb
spec/models/slot_spec.rb
spec/rails_helper.rb
spec/tasks/fix_appointments_spec.rb

Related to  https://github.com/betagouv/mon-suivi-justice/actions/runs/5916422741/job/16043689883 (No ticket created in Notion @damienlethiec )

fixed all the flaky tests failing on non open days

---

app/controllers/appointments_bookings_controller.rb

Linting problem created by the merge of `update-rails` into `develop`

linting in appointment controller

---

app/controllers/appointments_reschedules_controller.rb
app/models/user.rb
app/policies/appointment_policy.rb
app/policies/appointments_reschedules_policy.rb
app/policies/concerns/appointment_hability_checkable.rb
app/views/appointments/show.html.erb
spec/policies/appointment_policy_spec.rb
spec/policies/appointments_reschedules_policy_spec.rb

https://www.notion.so/monsuivijustice/fd8ba8a995c44c548cea70af972db86b?v=28c0db07a59f4d4285caa55ec8711cd2&p=45488e429d9d42cb81bf58a6130d6c33&pm=c

[MSJ-656] Prevent reschedule of canceled appointment

---

app/views/bex/agenda_jap_pdf.html.erb

strftime is called on `date` which is already a string

Agenda jap pdf edition is ko

---

app/assets/javascripts/administrate/application.js
app/controllers/admin/import_convicts_controller.rb
app/controllers/admin/import_srjs_controller.rb
app/controllers/admin/organizations_controller.rb

See https://github.com/thoughtbot/administrate/commit/15c49a619995c653ddd0bfa2d9ea4110c5c0fc0d

[MSJ-857] removed jquery ujs from administrate

---

app/assets/stylesheets/appointments.css
app/controllers/appointments_controller.rb
app/controllers/appointments_reschedules_controller.rb
app/javascript/controllers/appointment_new_controller.js
app/jobs/sms_delivery_job.rb
app/models/appointment.rb
app/models/convict.rb
app/models/notification.rb
app/views/appointments/new.html.erb
config/locales/fr.yml
spec/factories/appointment.rb
spec/features/appointment_extra_fields_spec.rb
spec/features/appointments_spec.rb
spec/features/convicts_spec.rb
spec/features/notification_types_spec.rb
spec/features/notifications_spec.rb
spec/tasks/fix_appointments_spec.rb

[MSJ-747] Send sms convoc

---

app/assets/stylesheets/application.postcss.css
app/assets/stylesheets/dsfr_custom.css
app/views/convicts/show.html.erb
config/locales/fr.yml

[MSJ-219] Feature/add a second create appointment button

---

.github/workflows/main.yml
Gemfile
Gemfile.lock
app/assets/config/manifest.js
app/javascript/application.js
app/javascript/appointment_new.js
app/javascript/components/city_selector.js
app/javascript/components/convict_selector.js
app/javascript/components/profile_search.js
app/javascript/convict_new.js
config/environments/test.rb

This reverts commit b9ad4668c77cc73ae824daa15d613cc4dd1c4f9e.

Revert "fix esbuild vs postcss conflict (#499)"

---

app/views/convicts/new.html.erb
app/views/home/home.html.erb
app/views/shared/_convicts_list.html.erb

Forgot to add the pagination helper to the convict list template

Added pagination to turbo template

---

app/models/agenda.rb
app/models/appointment.rb
app/policies/agenda_policy.rb
app/policies/appointment_policy.rb
spec/models/agenda_spec.rb

Fix convict show involving sap ddse and display of agenda ddse in bex controller

Fix ddse agenda

---

app/controllers/admin/public_pages_controller.rb

Tentative pour résoudre le problème lié à la création la récupération de la ref de la branche nouvellement créée.

now using github response to get the newly created branch

---

app/javascript/appointment_index.js

[MSJ-897] Users should be able to hand type dates in appointment index date filter

---

app/assets/stylesheets/application.postcss.css
app/controllers/slots_batches_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/pick_multiple_dates_controller.js
app/views/slots_batches/new.html.erb
package.json
spec/features/slots_spec.rb
spec/models/slot_spec.rb
yarn.lock

[MSJ-920] improve multiple slot creation

---

app/controllers/appointment_types_controller.rb

Fix redirect update notification type

---

app/views/appointments_reschedules/new.html.erb
app/views/convicts/show.html.erb

Suppression d'un warning plus d'actualité et ajout du type de convocation dans la liste des convocations à venir dans le show du probationnaire

Small fix for Cyril workflow

---

app/views/shared/_convict_row.html.erb

Fix https://sentry.incubateur.net/organizations/betagouv/issues/82359/?referrer=alert_email&alert_type=email&alert_timestamp=1705655890827&alert_rule_id=7&environment=staging

Add defaut to date of birth if nil

---

app/mailers/user_mailer.rb

Fix https://sentry.incubateur.net/organizations/betagouv/issues/82973/?alert_rule_id=7&alert_timestamp=1706091958001&alert_type=email&environment=production&project=14&referrer=alert_email

Fix admin nil error

---

app/assets/stylesheets/utilities.css
app/models/convict.rb
app/views/shared/_convict_row.html.erb
app/views/shared/_convicts_list.html.erb
spec/features/convicts_spec.rb
spec/support/shared_examples/convict_search_examples.rb

[MSJ-94] Convict table

---

app/jobs/appi_import_job.rb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/shared/_environment_alert.html.erb
config/initializers/sentry.rb
config/locales/fr.yml
lib/tasks/invite_convicts_to_interface.rake
spec/tasks/invite_convicts_to_interface_spec.rb

[MSJ-990] Add notice for staging and demo env

---

app/assets/stylesheets/dsfr_custom.css
app/models/appointment.rb
app/views/convicts/show.html.erb
app/views/shared/_convict_row.html.erb
app/views/slots/index.html.erb
config/locales/fr.yml
spec/features/slots_spec.rb
spec/models/appointment_spec.rb

Add validation to prevent appointment for discarded convict (+ change color delete convict button)

---

app/models/convict.rb
spec/factories/convict.rb
spec/models/convict_spec.rb

Le trio date de naissance, nom et prénom doit être unique sauf si la date de naissance est nil (si le current_user est admin) et sauf si les numéros APPI sont différents (donc pas tous nil)

[MSJ-934] Better dob handling

---

app/controllers/appointments_controller.rb
app/controllers/concerns/inter_ressort_flashes.rb
app/controllers/slots_controller.rb
app/helpers/appointments_helper.rb
app/views/slots/edit.html.erb
config/locales/fr.yml

Fixe https://github.com/betagouv/mon-suivi-justice/security/code-scanning/4 et toutes les autres occurences du problème

Escape unsafe html safe

---

app/helpers/convicts_helper.rb

https://mattermost.incubateur.net/betagouv/pl/issyp4sck7fwiyioepj311q6yh

Fix automatical selection followed by when local admin

---

app/views/bex/agenda_jap.html.erb
app/views/bex/agenda_jap_pdf.html.erb
app/views/bex/agenda_sap_ddse.html.erb
app/views/bex/agenda_sap_ddse_pdf.html.erb
app/views/bex/agenda_spip.html.erb
app/views/bex/agenda_spip_pdf.html.erb
spec/features/appointment_extra_fields_spec.rb

- Nom et prénom réunis pour gain de place
- Suppression du gras dans le body des tableaux
- Liens en bleu pour s'adapter aux habitudes des agents

Improve style bex agenda

---

app/controllers/users_controller.rb

Fix un peu urgent @Arahir . On pourra le mettre en ligne ASAP avec le JAPAT (je passe sur la review)

Fix bug which makes role change when organization changes

---

app/models/divestment.rb
app/services/divestment_state_service.rb
spec/services/divestment_state_service_spec.rb

https://www.notion.so/monsuivijustice/city-related-to-divestment-4787ad1ebdb14dbd8b3e9dadc62702c4?pvs=4

fix handling of city during inter ressort divestment

---

app/services/divestment_stalled_service.rb
spec/services/divestment_stalled_service_spec.rb

Only send 1 email admin per day

---

app/assets/stylesheets/main.css
app/controllers/appointments_controller.rb
app/controllers/appointments_reschedules_controller.rb
app/models/appointment.rb
app/models/convict.rb
app/policies/appointment_policy.rb
app/policies/appointments_reschedules_policy.rb
app/views/appointments/_cancel_appointment_modal.html.erb
app/views/appointments/show.html.erb
app/views/appointments_reschedules/new.html.erb
app/views/convicts/show.html.erb
app/views/shared/_appointment_card.html.erb
config/locales/fr.yml
spec/features/appointments_spec.rb
spec/features/bex_spec.rb
spec/policies/appointment_policy_spec.rb

Cancel without sms

---

app/assets/stylesheets/convicts.css
app/views/shared/_history_items.html.erb

Clean history items style

---

app/controllers/slots_batches_controller.rb
config/locales/fr.yml

C'est ça qui créait le timeout chez l'agente de Camille
Bon, tu vas me dire que c'est quand ça m'arrange ahah. Mais la refonte des créneaux est pas pour tout de suite et j'ai pas trouvé mieux en quick fix rapide :)

Prevent internal of 0 for slots

---

app/models/slot.rb
app/views/bex/agenda_jap.html.erb
app/views/bex/agenda_jap_pdf.html.erb
app/views/bex/agenda_sap_ddse.html.erb
app/views/bex/agenda_sap_ddse_pdf.html.erb
app/views/bex/agenda_spip.html.erb
app/views/bex/agenda_spip_pdf.html.erb
spec/models/agenda_spec.rb

https://www.notion.so/monsuivijustice/0-G-rer-bug-de-cr-neaux-de-sortie-d-audience-ferm-s-avec-convocations-annul-es-10d9f0badeb980fcbe31e9aed67b70f9?d=1129f0badeb98068a9e1001c8598d935

Fix display closed slot

---

app/controllers/convicts_controller.rb
app/controllers/users_controller.rb

https://www.notion.so/monsuivijustice/fd8ba8a995c44c548cea70af972db86b?v=307102107ad04725a3a9697c1e4ff0e4&p=59358337df8247aba361b97537daeac4&pm=c

Improve order convicts and user index

---

app/views/appointments/_convict_phone_status.html.erb
app/views/appointments/new.html.erb

Display alert on new appointment

---

app/controllers/unsubscribe_controller.rb
app/models/convict.rb
app/services/link_mobility_adapter.rb
spec/features/stop_sms_spec.rb

remove dead code and fix tests

cleanup stop sms

---

app/assets/stylesheets/administrate/application.scss
app/controllers/admin/convicts_controller.rb
app/services/convicts/merge_service.rb
app/views/admin/application/_navigation.html.erb
app/views/admin/convicts/merge_form.html.erb
app/views/admin/convicts/merge_preview.html.erb
config/routes.rb

Allow admin to merge convicts
