betagouv/mon-suivi-justice

- .rubocop.yml
- app/controllers/places_controller.rb
- app/controllers/users_controller.rb
- app/models/convict.rb
- app/models/place.rb
- app/models/user.rb
- app/policies/convict_policy.rb
- app/policies/place_policy.rb
- app/policies/user_policy.rb
- spec/features/users_spec.rb
- spec/models/convict_spec.rb
- spec/models/place_spec.rb
- spec/models/user_spec.rb
Crée un scope `.in_department` pour les convict, les lieux et les users pour pouvoir afficher seulement les bonnes données aux utilisateurs du bex et aux admins locaux.
Traite les tickets suivants :
https://trello.com/c/i7pBsSV3/500-habilitations-choix-du-d%C3%A9partement-ou-juridiction-de-la-ppsmj
https://trello.com/c/DEiI55lR/499-habilitations-en-tant-quadministrateur-de-ressort-je-veux-ne-voir-safficher-que-les-informations-de-mon-propre-ressort-et-ne-pas
> Restrict access to data by department

- app/assets/stylesheets/appointments.scss
- app/controllers/appointments_controller.rb
- app/javascript/components/slot_selector.js
- app/models/agenda.rb
- app/models/appointment.rb
- app/models/appointment_type.rb
- app/models/place.rb
- app/policies/appointment_policy.rb
- app/views/appointments/_display_slot_fields.html.erb
- app/views/appointments/display_slot_fields.js.erb
- app/views/appointments/new.html.erb
- app/views/places/edit.html.erb
- app/views/slot_types/index.html.erb
- app/views/slots/new.html.erb
- config/routes.rb
- db/seeds.rb
- spec/features/appointments_spec.rb
- spec/features/convicts_spec.rb
- spec/features/slot_types_spec.rb
- spec/features/slots_spec.rb
- spec/models/agenda_spec.rb
- spec/policies/appointment_policy_spec.rb
Tout le système de créneau est limité aux types de rdv "Sortie d'audience SPIP" et "Sortie d'audience SAP".
Lors de la création d'un rdv, on a maintenant le choix entre deux modes de fonctionnement : 
- Complet, avec des créneaux issus de créneaux récurrents, pour les types de rdv "Sortie d'audience SPIP" et "Sortie d'audience SAP"
- Light, avec des champs pour saisir la date et l'heure du rdv directement
Dans la zone de gestion des créneaux récurrents, on ne peut plus en créer pour d'autres types de rdv que les deux prévus
Lors de la création d'un créneau, on ne peux choisir que les deux types de rdv adaptés.
> Upgrade slot system

- app/models/convict.rb
- app/services/data_collector.rb
Exclut ceux avec un téléphone égale à la string vide et ceux qui n'en ont pas du tout
https://thoughtbot.com/blog/activerecord-s-where-not-and-nil
https://trello.com/c/9b1sPevD/707-bug-stats
> Add to user without phones the ones with a blank phone

- app/policies/agenda_policy.rb
- app/policies/application_policy.rb
- app/policies/appointment_policy.rb
- app/policies/convict_policy.rb
- app/policies/place_policy.rb
- app/views/appointments/index.html.erb
- app/views/slots/index.html.erb
A priori on avait un agent non lié à un département. L'erreur n'est arrivée qu'une fois donc on peut laisser filer. Mais si ça arrive à nouveau faudra sans doute gérer des validations.
J'ai proposé malgré tout un petit changement car l'origine de la variable organization était assez peu claire de mon point de vue + elle n'était pas utiliser tout le temps.
Par contre, question: je trouve ça super étonnant dans les policies de n'afficher que les ressources liées au premier département d'une personne. Pourquoi ne pas lui afficher ressources liées à son organization? Si une personne doit avoir un département d'attache, il faudrait créer ce lien user/organization plutôt que de faire un `.first` non? Chaud pour avoir le contexte demain ;) …
> Remove organization variable from policies

- app/controllers/appointments_reschedules_controller.rb
- app/jobs/sms_delivery_job.rb
- app/models/appointment.rb
- app/models/notification.rb
- spec/factories/convict.rb
- spec/features/notifications_spec.rb
- spec/jobs/sms_delivery_job_spec.rb
https://trello.com/c/S1PxPguD/809-proposer-denvoyer-un-sms-de-rappel-lorsquon-ajoute-un-num%C3%A9ro-de-tel-%C3%A0-une-ppsmj-dont-le-rdv-avait-%C3%A9t%C3%A9-fix%C3%A9-sans-num%C3%A9ro
> Send sms when phone is added later

- app/models/organization.rb
Relates to https://www.notion.so/monsuivijustice/Augmenter-le-nombre-de-date-du-select-agenda-JAP-20-dates-au-lieu-de-10-0098d0a7cd1d41278d4741636ef3c05a
> now selecting first 20 slots instead of 10

- app/policies/appointment_policy.rb
- spec/features/appointments_spec.rb
- spec/policies/appointment_policy_spec.rb
related to: https://www.notion.so/monsuivijustice/PPSMJ-transf-r-e-de-service-ne-plus-faire-apparaitre-les-boutons-absence-pr-sence-un-RDV-77315450c4fc4a8faa9e6b435a96c0ef
> Prevent user from fulfiling appointment from other service

- app/jobs/execute_stored_procedures_job.rb
- config/clock.rb
Relates to https://www.notion.so/monsuivijustice/Cr-er-les-proc-dures-stock-es-sur-msj-prod-pour-metabase-a0f6c85f24424578a95abc53e1c0f7da
These stored procedures are meant to populate `model_probationnaire`, `model_appointments` and `model_sms` tables which are used by MetaBase.
> added execute stored procedures job

- app/controllers/application_controller.rb
When admin impersonate regular users, we want to be able to track their actions in papertrail.
> override papertrail user method

- app/controllers/admin/import_convicts_controller.rb
- app/jobs/appi_import_job.rb
- app/mailers/admin_mailer.rb
- app/views/admin_mailer/appi_import_report.html.erb
Les exports APPI contiennent probablement des erreurs de syntaxe. Le script d'import les rescue et les ajoute à la liste d'erreurs envoyée par mail à l'admin.
> APPI import should not crash because of syntax errors

- app/models/agenda.rb
related to: https://www.notion.so/monsuivijustice/Affichage-dans-l-agenda-de-cr-neaux-sortie-d-audience-SPIP-ferm-s-d9587320a45049db9ebf543849e2d7d0?pvs=4
> Only display available slots in agendas

- app/controllers/appointments_controller.rb
- app/views/appointments/new.html.erb
Fix extra fields for inter ressort and intra ressort
warning: now extra fields only work if a convict is already selected when creating a new appointment (`/appointment/new?convict_id=...`
> Fix extra fields

- app/policies/convict_policy.rb
related to https://www.notion.so/monsuivijustice/Les-admins-locaux-TJ-ne-doivent-pas-pouvoir-d-sattribuer-un-CPIP-d-une-PPSMJ-2d1cbdcc3605422d8795583f3ed0873b?pvs=4
> forbid local admin tj from unassigning cpip

- config/clock.rb
Relates to https://www.notion.so/monsuivijustice/Refaire-fonctionner-les-proc-dures-Postgres-alimentant-nos-models-Metabase-f8f1dd4ceae94cb1a2bd2eecd4ddb790?pvs=4
L'exécution des procédures stockées peuplant les models destinés à Metabase n'était pas déclenchée la nuit comme prévu.
> fixed env var error in for stored procedures job

- app/services/data_collector/user.rb
Relates to https://www.notion.so/monsuivijustice/Widget-de-stats-utilise-toujours-under_hand_of-51ca98bae50745c6b46e9e45d5e3fd9a?pvs=4
> fixed stats by service

- app/views/home/_home_stats.html.erb
"% de présence" was displaying nothing.
> fixed typo in home stats widget

- app/models/convict.rb
- spec/models/convict_spec.rb
- spec/policies/convict_invitation_policy_spec.rb
Relates to https://www.notion.so/monsuivijustice/Les-num-ros-de-t-l-phone-de-l-quipe-sont-en-clair-dans-le-repo-c7348c1926a14339af63b1d42c123164?pvs=4
On supprime totalement la fonctionnalité des WHITELISTED_PHONES
> removed whitelisted phones feature

- app/controllers/convicts_controller.rb
- app/models/convict.rb
- spec/models/convict_spec.rb
related to https://www.notion.so/monsuivijustice/Impossible-de-cr-er-un-probationnaire-quand-on-peut-utiliser-l-inter-ressort-18c61132291a409ebefa0b72e35aabcd?pvs=4
> Fix create convict bex

- app/controllers/admin/convicts_controller.rb
related to https://www.notion.so/monsuivijustice/Permettre-la-mise-jour-des-PPSMJs-sans-date-de-naissance-depuis-l-interface-administrate-0d3f34877acf4c51814aa2c9dc21cbfc?pvs=4
> Allow to modify ppsmj without date of birth in administrate

- app/controllers/bex_controller.rb
- app/models/agenda.rb
- app/models/slot.rb
- spec/models/slot_spec.rb
related to https://www.notion.so/monsuivijustice/Le-menu-d-roulant-de-choix-des-dates-des-tableaux-sortie-d-audience-affiche-des-dates-sans-cr-neaux-2caeb1c5a4c44ea698a5ccc488a333b1?pvs=4
> Fix display date on bex agenda

- lib/tasks/fix_appointments.rake
- spec/tasks/fix_appointments_spec.rb
- Retrieve all 'created' appointments during the redis failure on Friday, August 11th
- Check for a 'booked' appointment with the same convict_id, slot date, and starting time
- If conflicting appointment found, delete the 'created' appointment
- If no conflicting appointment found, book the appointment using state machine and make sure it sends the sms
> rake task to fix appointments after redis incident

- app/controllers/admin/seeds_controller.rb
- app/dashboards/organization_dashboard.rb
- app/jobs/prepare_place_transfert_job.rb
- db/schema.rb
FTR : l'essentiel du supposé bug était en fait une erreur utilisateur. Le numéro de téléphone du nouveau lieu n'a pas été mis à jour tout de suite mais bien une semaine après la date de déménagement. C'est pour cette raison que les rendez-vous créés avant la mise en place du nouveau numéro de téléphone avaient des notifs erronées
> [MSJ-603] Bugfix/missed appointment popups use legacy place after transfert

- app/controllers/convicts_controller.rb
Les utilisateurs bex ne peuvent pas ajouter de date de naissance à un probationnaire existant qui n'en a pas.
> removed useless validation context for bex

- app/models/agenda.rb
- app/models/appointment_type.rb
Sorting in appointments index is K.O because of missing ransackable attributes and assocations
> added proper ransackable attributes and assocations

- app/views/convicts/show.html.erb
Should have been a link_to like the button at the bottom of the page
> New appointment creation button on convict show is KO

- spec/features/users_spec.rb
Le test 'allows to delete user' est flaky parce que le premier utilisateur de la liste est l'admin et ne peut pas être supprimé.
Il arrive que l'admin soit en tête de liste et que donc le teste ne passe pas.
> Fix flaky test in users spec

- app/assets/stylesheets/appointments.css
- app/assets/stylesheets/index.css
- app/helpers/appointments_helper.rb
- app/views/shared/_appointments_table.html.erb
- config/initializers/ransack.rb
Impossible d'utiliser des icônes remixicon dans la conf de ransack. 
Les helpers d'assets ne fonctionnent pas dans ce contexte. 
Voici une alternative.
> Manually added expand arrows to appointments table sorting links

- app/controllers/convicts_controller.rb
- app/models/organization_divestment.rb
- app/services/divestment_creator_service.rb
- spec/features/divestments_spec.rb
- spec/models/convict_spec.rb
- spec/services/divestment_creator_service_spec.rb
Evolution poste réu des ambassadeurs: pour un probationnaire donné, s’il est lié à un ou des TJ, ce sont seulement eux qui peuvent valider le dessaisissement. S’il n’est pas lié à des TJ c’est son ou ses SPIPs qui doivent le faire. Même si le le SPIP n’a pas son mot a dire, il est quand même prévenu.
—> Proposition : Le SPIP est passé en automatiquement validé s’il n’a pas de réponse à donner.
> [MSJ-980] spip auto accept

- app/models/convict.rb
- app/services/divestment_stalled_service.rb
- spec/models/convict_spec.rb
- spec/services/divestment_stalled_service_spec.rb
l'auto acceptation des divestments est bloqué quand un agent bex prend un rdv apres creation du dessaisissement a cause de last_appointment_in_the_past?.
Dans cette PR, on verifie a la place si le probationnaire a des convocations dans le futur uniquement dans le service cible du dessaisissement ou ses organizations liée
> Fix future app divestment
